name: "User Story"
description: "Template for Agile User Story"
title: "[US-XX]: "
labels: ["user story"]
body:
  - type: textarea
    id: story
    attributes:
      label: "User Story"
      description: "Write in the format: As a [role], I want [goal], So that [benefit]"
  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria"
      description: "Use Given / When / Then format"
      value: |
        Given ...
        When ...
        Then ...
  - type: textarea
    id: subtasks
    attributes:
      label: "Sub-tasks"
      value: |
        - [ ] Backend task
        - [ ] Frontend task
        - [ ] Testing
  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Assumptions, dependencies, or related links"
